config/routes.rb
Rails.application.routes.draw do
 resources :questions do
  resources :answers
 end
 resources :users, except: [:index, :destroy]
 get "/sessions" => "sessions#destroy"
 resources :sessions, only: [:new, :create]
 root "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_secure_password
  validates :email, uniqueness: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_question, only:[:create, :destroy]
  def create
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
    redirect_to question_path(@question)
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.delete
    redirect_to question_path(@question)
  end

  private
  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
    def current_user
      @current_user ||= User.find_by id: session[:user_id]
    end

  def authorize
    unless current_user
      redirect_to new_session_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :question_find, only: [:show, :destroy, :edit, :update]
  before_action :authorize, except: [:index, :show]
  def index
    @questions = Question.all.page params[:page]
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(questions_params)
    @question.user_id = current_user.id
    if @question.save
      redirect_to questions_path
    else
      redirect_to new_questions_path
    end
  end

  def edit
    @question
  end

  def update
    @question.update(questions_params)
    if @question.save
      redirect_to questions_path
    else
      redirect_to new_questions_path
    end
  end

  def show
    @question
  end

  def destroy
    @question = Question.find(params[:id])
    @question.delete
    redirect_to questions_path
  end

  private

  def questions_params
    params.require(:question).permit(:title, :body)
  end

  def question_find
    @question = Question.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @current_session = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if @current_session
      session[:user_id] = @current_session.id
      redirect_to questions_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to questions_path
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuestionBox</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
    <%= link_to "logout", sessions_path %>
    <%= link_to "profile", current_user %>
    <% else %>
      <%= link_to "login", new_session_path %>
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <%= link_to "home", questions_path %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/questions/index.html.erb
<h1>Questions Box</h1>
<%= link_to "Create New Question", new_question_path %>
<hr />
<% @questions.each do |question| %>
  <h1><%= link_to question.title, question %></h1>

  <p>
    <%= markdown(question.body) %>
  </p>
  <h5>Published <%= time_ago_in_words question.created_at %> ago</h5>
  <% if current_user && question.user_id === current_user.id %>
  <%= link_to "Delete", question, method: :delete %>
  <%= link_to "Edit",  edit_question_path(question) %>
  <% end  %>
  <% if question != @questions.last %>
  <hr />
  <% end %>
<% end %>
<%= paginate @questions %>

app/views/questions/new.html.erb
<h1>Create a new Question</h1>

<%= render "form" %>

<%= link_to "Back", questions_path %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<hr />

<p>
  <%= markdown(@question.body) %>
</p>
<h4>Published <%= time_ago_in_words @question.created_at %> ago</h4>
<%= link_to "Back to Index", questions_path %>

<hr>
<h2>Answers</h2>
<% @question.answers.each do |answer| %>
    <p>
    <%= answer.body %>
    <p>Published <%= time_ago_in_words answer.created_at %> ago</p>
    </p>
  <% if current_user && current_user.id === @question.user_id %>
    <%= link_to "Approve Answer", question_path %>
  <% end %>

  <% if current_user && current_user.id === answer.user_id %>
    <%= link_to "Delete", question_answer_url(@question, answer), method: :delete %>
  <% end %>
<% end %>
<hr>


<h2>Add an Answer</h2>
<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>User profile</h1>
<% @user.questions.each do |question| %>
  <%= question.title %>
  <br>
<% end  %>